process.env.PEM_KEY = `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEINofexMSQApYFYPK1/oISaOG4BgHm9SEkiHRUQOcmloToAoGCCqGSM49
AwEHoUQDQgAEoRFl5IWEgK9PTCvI8lzT1kBdvFvVw/EZzKT8XHQczrBnVSc+S8qw
tQrWvRJknz7jP0GHpvUm2GXHx6aOcbdBag==
-----END EC PRIVATE KEY-----`;
