name: Code quality

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version-file: "./package.json"

      - name: Install dependencies
        run: bun i

      - name: Check format and lint checks
        run: bun run ci

      - name: Other checks
        run: bun turbo build check-types check-exports test
