name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          version: 1.2.15

      - name: Install dependencies
        run: bun i

      - name: Install Global Dependencies
        run: bun install turbo --dev

      - name: Check format and lint checks
        run: bun run ci

      - name: Other checks
        run: bun turbo check-types
